### PR TITLE
[RFR] Fix queries & architecture

### LINKED ISSUE #5: Use link from copostgresquery
See https://github.com/marmelab/javascript-boilerplate/pull/148/files#diff-d069c09ce3ea5c380a686ce3820b24d4R10

### PR DESCRIPTION
**Pull request by floo51**
- [x] Rename cowrap to λ
- [x] Implement async to gen
- [x] Implement co-postgres-queries in all queries
- [x] Release client
- [x] Fix queries

Fixes #5

### CODE REVIEW

File: api/src/queries/environments.js [hunk 1]
```diff
@@ -2,42 +2,58 @@ import { crudQueries } from 'co-postgres-queries';
...
-const insertOne = function* (environment) {
-    const client = yield db.client();
-    return yield client.query(
-        base.insertOne(environment),
-    );
+query.selectPage
+    .table('environment LEFT JOIN configuration ON (environment.id = configuration.environment_id)')
+    .idFields(['id'])
+    .searchableFields(['environment.name', 'project_id', 'environment.state'])
+    .returnFields(['environment.id', 'environment.name', 'case when count(configuration.name) = 0 then \'[]\' else json_agg((SELECT x FROM (SELECT configuration.id, configuration.name, configuration.default_format as "defaultFormat") x)) end as configurations'])
```
Comment (Kmaschta) [inline api/src/queries/environments.js]: ``configuration.default_format as "defaultFormat"
wut?
